//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanchaConexion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jugadores
    {
        public int id_jugadores { get; set; }
        public string rut { get; set; }
        public string nombre { get; set; }
        public System.DateTime edad { get; set; }
        public int comuna { get; set; }
        public Nullable<bool> eliminado { get; set; }
        public Nullable<System.DateTime> fecha_elim { get; set; }
        public string cliente { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Comunas Comunas { get; set; }
    }
}
