//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanchaConexion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservas
    {
        public int id_reserva { get; set; }
        public string cliente { get; set; }
        public int cancha { get; set; }
        public Nullable<bool> confirmacion { get; set; }
        public string comentarios { get; set; }
        public Nullable<int> monto_abono { get; set; }
        public Nullable<int> monto_total { get; set; }
        public string metodo_pago { get; set; }
        public Nullable<int> cant_personas { get; set; }
        public Nullable<int> equipo_a { get; set; }
        public Nullable<int> equipo_b { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual Canchas Canchas { get; set; }
        public virtual Clientes Clientes { get; set; }
    }
}
